### ISSUE TITLE
systemd is not working

### ISSUE THREAD

**Issue by zarr12steven** [olipo186/Git-Auto-Deploy#107]
##### ENVIORNMENT
remote server: CentOS Linux release 7.2.1511 (Core)

##### SYSTEMD

`-rw-r--r--. 1 root root 238 Jun 21 16:54 /etc/systemd/system/git-auto-deploy.service`

```
[Unit]
Description=GitAutoDeploy

[Service]
User=root
Group=root
WorkingDirectory=/opt/Git-Auto-Deploy/
ExecStart=/usr/bin/python /opt/Git-Auto-Deploy/gitautodeploy --config config.json --daemon-mode

[Install]
WantedBy=multi-user.target
```

##### CONFIG JSON

`-rwxr-xr-x. 1 root root 466 Jun 21 17:08 /opt/Git-Auto-Deploy/config.json`

```
{
  "pidfilepath": "/var/run/gitautodeploy.pid",
  "logfilepath": "/var/log/gitautodeploy.log",
  "host": "0.0.0.0",
  "port": 8001,
  "global_deploy": [
    "echo Deploy started!",
    "echo Deploy completed!"
  ],
  "log-level": "INFO",
  "repositories": [
    {
      "url": "git@gitlab.example.com:nobody/repo.git",
      "branch": "master",
      "remote": "origin",
      "path": "/etc/ansible/repo",
      "deploy": "echo deploying..."
    }
  ]
}
```

##### /root/.ssh/config

```
HOST gitlab.example.com
    HostName gitlab.example.com
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null
    IdentityFile ~/.ssh/deploy
```

##### ISSUE

```
systemctl status git-auto-deploy
● git-auto-deploy.service - GitAutoDeploy
   Loaded: loaded (/etc/systemd/system/git-auto-deploy.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Tue 2016-06-21 17:09:53 CST; 15min ago
  Process: 31058 ExecStart=/usr/bin/python /opt/Git-Auto-Deploy/gitautodeploy --config config.json --daemon-mode (code=exited, status=0/SUCCESS)
 Main PID: 31058 (code=exited, status=0/SUCCESS)
```

```
ps -ef | grep 31058
root     31094 30607  0 17:33 pts/0    00:00:00 grep --color=auto 31058
```

```
ps -axu | grep python
root     19104  0.0  1.5 553072 16216 ?        Ssl  15:11   0:01 /usr/bin/python -Es /usr/sbin/tuned -l -P
root     19229  0.0  2.2 323588 23156 ?        Ssl  15:12   0:00 /usr/bin/python -Es /usr/sbin/firewalld --nofork --nopid
root     31096  0.0  0.0 112648   932 pts/0    R+   17:33   0:00 grep --color=auto python
```

when i check `ls /var/run/ | grep gitautodeploy.pid` , can't not find the file.

why the process is dead, and also not create the pidfile. am i set up wrong or missing something ?

**Comment by olipo186** [comment]
Do you have any entries in ```/var/log/gitautodeploy.log```?

Also, try specifying the absolute path for the config file:

    ExecStart=/usr/bin/python /opt/Git-Auto-Deploy/gitautodeploy --config /opt/Git-Auto-Deploy/config.json --daemon-mode

**Comment by olipo186** [comment]
@zarr12steven, were you able to get it working?

**Comment by zarr12steven** [comment]
@olipo186  still not working....

i already setting absolute path in `/etc/systemd/system/git-auto-deploy.service`

```
[Unit]
Description=GitAutoDeploy

[Service]
User=root
Group=root
WorkingDirectory=/opt/Git-Auto-Deploy/
ExecStart=/usr/bin/python /opt/Git-Auto-Deploy/gitautodeploy --config /opt/Git-Auto-Deploy/config.json --daemon-mode

[Install]
WantedBy=multi-user.target
```

this is my gitautodeploy.log
```
2016-07-01 18:25:19,066 [INFO ]  Starting Git Auto Deploy in daemon mode
2016-07-01 18:29:37,924 [INFO ]  Repository gitlab.example.com:daniel_lin/ssh_keys.git not present and needs to be cloned
2016-07-01 18:29:38,956 [INFO ]  Cloning into '/root/ssh_keys'...
2016-07-01 18:29:38,956 [INFO ]  Repository gitlab.example.com:daniel_lin/ssh_keys.git successfully cloned
2016-07-01 18:29:38,957 [INFO ]  Starting Git Auto Deploy in daemon mode
```

if i clean my repo, and i first start `system start git-auto-deploy`, i can see the repo already cloned,but when i send `git push` for ssh_keys.git, it not working.

**Comment by olipo186** [comment]
I cannot help you further as this sounds like a problem related to your setup or environment (based on CentOS and systemd) rather than an error in the code of GAD. Sometimes I can help out and provide support for these kind of issues on ubuntu systems, since that's what I'm using myself - but in this case I don't have much to offer.

If you figure it out and get it working, please reopen the issue or get back to me with how you did. If the solution contained any special steps related to the systemd script or CentOS in general, it could be useful information that we can put into a step by step install guide for CentOS/systemd.

**Comment by raffo89** [comment]
I know this issue is now closed, but i has the same and i found this thread. So i solved and i want to let you know what is the issue.

The main problem is the Working Directory, if you change it, you must change also the path of the script you run.

`WorkingDirectory=/opt/Git-Auto-Deploy/
ExecStart=/usr/bin/python /opt/Git-Auto-Deploy/gitautodeploy --config /opt/Git-Auto-Deploy/config.json --daemon-mode`

This mean: $WorkingDirectory//usr/bin/python /opt/Git-Auto-Deploy/gitautodeploy
(systemd see /opt/Git-Auto-Deploy//usr/bin/python /opt/Git-Auto-Deploy/gitautodeploy).

You must put `WorkingDir=/ ` if you want fix you script.

Or use relative path in ExecStart

```
[Unit]
Description=Autodeploy Frontweb vhosts Service
After=syslog.target network.target remote-fs.target nss-lookup.target

[Service]
WorkingDirectory=/opt/Git-Auto-Deploy/
ExecStart=/usr/bin/python gitautodeploy --config config.json --deamon-mode
ExecStop=/bin/kill -9 -s QUIT $MAINPID
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
```
