### ISSUE TITLE
detailed-response option not work

### ISSUE THREAD

**Issue by realsby** [olipo186/Git-Auto-Deploy#137]
or I cant find how to set it properly.. 
I changed this files.
vim /usr/lib/python2.7/dist-packages/gitautodeploy/cli/config.py
vim /var/lib/git-auto-deploy/Git-Auto-Deploy/gitautodeploy/cli/config.py

I even add it to git-auto-deploy.conf.json like
  "detailed-response": "False",

Then restart service but still same result. Am i missing something?

**Comment by realsby** [comment]
service git-auto-deploy restart doesnt compile python files. How can I set new conf.

**Comment by realsby** [comment]
I fixed my problem.. Tried lots of things.. I am not sure how, why it works acctualy.. 

But right now I am trying secret-token option..  It seems doesnt work properly..  

In my config.json i added a dummy secret token like "secret-token": "lcbzpbh",  then restart g-a-d service..   But on my gitlab hook, secret-token is empty..  When i push something git auto deploy still  works..

**Comment by olipo186** [comment]
Good to hear that you got it working at last. The "detailed-response" option was removed recently due to other changes in application. Deploy commands are now executed as python threads and the HTTP response to the caller (the git service) is now always sent immediately.

About the "secret-token" issue, it might be related to a bug in the same area that was fixed within this issue https://github.com/olipo186/Git-Auto-Deploy/issues/176
