### ISSUE TITLE
please do include basic setup information

### ISSUE THREAD

**Issue by Jossnaz** [olipo186/Git-Auto-Deploy#173]
great program

but i don't know as what user the service runs, there are permission problems

now i have to figure it out, maybe just give it 777
oh then you disable the key files
ok
the service runs as git-auto-deploy

so I guess we pull the project, then create a shellscript to move it to the server root? so add the user to the group that has write access to the server root?

before that your example using https was bad, because private repos would ask for username and password

the normal repo is private, right. not public.

feeling like i lost quite some time setting it up and this will barricade access to your lib for a lot of people

**Comment by olipo186** [comment]
Hi,

If you find things that needs improvements or more work, please submit them in a PR.

**Comment by Letme** [comment]
I do not see why you need username and password if you use deploy key - just btw. And giving a 777 permission on any file is like throwing away security...

**Comment by Jossnaz** [comment]
I did need username password for https. Not for git protocol though. why? ask gitlab

the installation lacks basic information about:
what user does the server run in

how to write a shell script that can say, perform the very very basic needs for a programmer to move the files from the gad folder to the server target folder and change the permissions to say sftp-user:www-data

yes yes, you can argue "but that depends on the use case"

if you don't want, you don't want. Thats ok.

**Comment by Letme** [comment]
Because you did not use deploy key I would assume?

Why does it matter what user does server run in? Server mostly needs read only permissions to html files or execute permissions, so you can just add it in same group as GAD.

There is a configuration.json.example file where you have two attributes commented:
```
"path": "Where do you want GAD to CLONE the repo (so no need to move around stuff")
"deploy": "chown -R sftp-user:www-data /path/to/whatever/you/want"
```

That good enough?

If you put a 777 then chowning is useless anyway.

**Comment by Jossnaz** [comment]
if i did not use keys on gitlab, how comes it did work with the git url?

if i don't know what user the gitlab server runs in, how can i run commands with sudo and without password? e.g. how can I do this:
http://askubuntu.com/questions/39281/how-to-run-an-application-using-sudo-without-a-password

if there is a simple clone error because the damned user of gad has no write access to that folder, how do I fix it without knowing the user of gad?

why would I clone a git repo directly onto a server, and eventually run the danger of exposing .git files that basically give complete access to source code? at laest thats what i read.
on a sidenote, have you ever tried cloning into a folder where there exists all files already, but are owned by a different user? does it work flawlessly for all cases? i would be surprised, haven't tried it though


that's probably a pretty good example of what you should not be doing. I might be wrong though.

**Comment by Letme** [comment]
And why would you switch to https then?

I do not understand why would you like to run application using `sudo without a password`. Add GAD user to group that has write access to that folder - simple as that. You can check as what user you run GAD as (if you do not know) simply by checking `ps aux | grep git-auto-deploy`.

To me it seems like you have permission problems and server setup problems.Where GAD clones once, it can clone twice. When web server shares files it needs to be in same group as GAD. GAD runs a web server (some kind of)...

It is true what you say about git files, but that just means that you need to setup your webserver so that it does not share .git folder (same as for secrets file). But this is again outside of GAD scope.
