### ISSUE TITLE
[ERROR]  The repository '/root/path/myrepo' does not exist locally. Make sure it was pulled properly without errors by reviewing the log.

### ISSUE THREAD

**Issue by fiantinangon** [olipo186/Git-Auto-Deploy#174]
Everytime i push always have this error

**Comment by Letme** [comment]
So you need to git-clone it in /pat/myrepo, then let git-auto-deploy do the work.

**Comment by fiantinangon** [comment]
i already do that :( but the problem still showing up, even when i already Chown my path to become git-auto-deploy:git-auto-deploy , the log still saying
```
could not create leading directories
```
please help

**Comment by fiantinangon** [comment]
i also try to clone the repo manualy, but why i still get this  error :(

**Comment by Letme** [comment]
Why are you changing the topic? Adding root to that path just seems plain wrong unless you run git-auto-deploy as root. When you have problems with permissions easiest thing to do in sudo systems is `sudo su username` and then try to do something as that user. I would say that if you cloned it as correct user and you run git-auto-deploy as same user that it should work. Otherwise we need a bit more info to advise.

**Comment by fiantinangon** [comment]
@Letme believe me i already do that 😄  , yes i think we need a bit more info about this thing
