### ISSUE TITLE
Hide and Sweek with Private Keys

### ISSUE THREAD

**Issue by Ne00n** [olipo186/Git-Auto-Deploy#183]
Hey,

I am trying to get Git-Auto-Deploy on Debian to work, I used Debian 8 for that.

Created a non privileged user, cloned Git-Auto-Deploy renamed the config, adjusted the config.
Generate a ssh keypair. moved booth the public and the private key to /home/user/Git-Auto-Deploy/.ssh

Started Git-Auto-Deploy, it only asks me for my Password, which seems like It cannot find my private key to auth with Github.

So, No error message, nothing, could you help me to find out where I need to Hide my Keys to Git-Auto-Deploy will find them?

Thanks.

Ne00n.

**Comment by olipo186** [comment]
Hi,

Did you manage to solve it? Please post your solution here for future reference. It's good to have when people with similar issues find this question using search engines etc.

**Comment by Ne00n** [comment]
Well sadly its not, but I did invested Enought time, so I guess I keep the good old git pull instead of this.

**Comment by Letme** [comment]
If you use git@ instead of https:// for repository cloning then you add your user's ssh-key (public) to Deploy-Keys, your git-pull should work? Or maybe I do not understand what your real problem is?

**Comment by Letme** [comment]
Another side note from re-reading. Ssh keys should be in user's home so /home/user/.ssh (you have git-auto-deploy there for some reason). Git-auto-deploy config does not need to be renamed, but you can pass it as a parameter to script if you do rename it.

**Comment by MarkAPitt** [comment]
I am experiencing a similar problem. Here are additional symptoms in my case. First off, I use git@ for this private repo, and my own ssh public key is on Github, and pushing and pulling work fine with the repository. Ubuntu 14.04. Installed GAD using PPA.

Upon starting the service, Git-Auto-Deploy requests my login credentials, as shown below. Upon providing them, deployment will succeed only with this first push.  Subsequent pushes fail until I stop the service and restart it again, so the problem would appear to be with credentialing. It is at this point I am not sure how to proceed. GDA is a member of the group that has access to the repository.  known_hosts in GAD is empty. My private key for Github is in the GAD folder, with ownership of GAD:GAD. I changed it and the paths to GAD:(dev_group), but this did not make a difference.

Username for 'https://github.com': Username
Password for 'https://Usernamet@github.com':

**Comment by Letme** [comment]
Remove https:// and use git@ ....

**Comment by Letme** [comment]
Maybe I am not clear enough. If you want SSH keys to be considered, then you must use username@ to clone (for example: `git@github.com:olipo186/Git-Auto-Deploy.git`) - otherwise it will ask you for username and password. That SSH key needs to be in GAD running user's `home/.ssh` folder (private and public part) as well as in GitHub as Deploy key (only public part).

**Comment by MarkAPitt** [comment]
Thank you for the url suggestion. It did indeed fix the problem being prompted for login credentials repeatedly. It did not solve the other problem I describe above, but I have finally determined its source after checking the GAD logs and doing a bit more testing. Here is an explanation in case it helps someone in the future.

Again, the symptom was that when the service started, the repo would be cloned but any subsequent push failed to clone. Only after restarting the service would another pull be executed. Although the two ports were open, it turns out that my institution's firewall was preventing the push from succeeding. There were no errors to this effect, so it took a while to isolate. When setting up the hook, I had forgotten to check that it actually succeeded, which it did not.
