### ISSUE TITLE
Not pulling automatically at all 

### ISSUE THREAD

**Issue by thetechguy61705** [olipo186/Git-Auto-Deploy#245]
I know I sound stupid, but `git-auto-deploy` is not detecting any change with the respository and its not pulling the code into the folder

I’m sure its just a configuration issue, but I’m not sure why its not pulling when I push to my repository

- Using the status command, everything looks normal
- Nothing is logged when I push to the respository

Any ideas?

**Comment by Letme** [comment]
Branch filter? What is in the logs?

**Comment by thetechguy61705** [comment]
I think I might know what the problem is, I’ll check that and come back. I think it was just a simple config error on my part. I’ll Close this if i figure it out

**Comment by thetechguy61705** [comment]
Is there any good tutorials on how to use this? I’m completely confuse on how to set it up. Do i need to make sure the port is open? And how do I set up the webhook in the repository

**Comment by Letme** [comment]
Depends where you want to open ports, but yes, ports you define in the configuration should be forwarded to you server, so that it can receive hooks and act upon them. 

Same for the webui, its ports needs to be accesible, from where you want to access it.

Documentation here seems a quite decent tutorial on how to do it, so please point out any deficiencies or even propose fixes...

**Comment by thetechguy61705** [comment]
I don’t feel the tutorial is that good. I followed it exactly and this thing is not working. It doesn’t even talk about GitHub webhook which god only knows if we need

**Comment by thetechguy61705** [comment]
Turns out I found the proper documentation! I didn't realize it wasn't on GitHub. 

I will read that and try again!

Thanks for everybody's help!
