### ISSUE TITLE
pyton setup

### ISSUE THREAD

**Issue by DirectorX** [olipo186/Git-Auto-Deploy#60]
add python setup.py file to make this project to a python package - `pip install git-auto-deploy` its also will support auto installation to `/usr/bin` or `/otp`

**Comment by DirectorX** [comment]
suggested project directory structure

Git-Auto-Deploy
├── initfiles
│   ├── init files here
│   └── ...
├── bin
│   └── main_executeable.py `will be install at /usr/bin`
├── gitautodeploy
│   ├── project source file
│   └── ...
├── Makefile `will be deleted`
├── LICENSE
├── README.md
└── setup.py `the installation file`

**Comment by DirectorX** [comment]
attention @olipo186 @alexandernst

**Comment by alexandernst** [comment]
I'm +1 for restructuring the project's file locations, but -1 for deleting the Makefile.
make is installed by default on all distros and removing the Makefile just removes well working features. 

Anyways, as you say, I must work on #9 (when I have some time)

**Comment by DirectorX** [comment]
update

@olipo186 @alexandernst

Git-Auto-Deploy
├── data
│   ├── init files
│   │   └──  ....
│   └── configuration file
├── gitautodeploy
│   ├── cli
│   │   ├──  argument parser
│   │   └──  `__init__.py` contains the main function
│   ├── gitwrapper
│   ├── httpserver
│   │   ├──  github handler
│   │   ├──  gitlab handler
│   │   └──  bitbacket handler
│   ├── config parser
│   ├── utils
│   │   └──  file system locks
│   └── `__init__.py` lib root
├── Makefile
├── LICENSE
├── README.md
├── requirements.txt
└── setup.py `the installation file`

**Comment by olipo186** [comment]
I've put some work in to improve the project file structure, much inspired by the above suggestions. It's now possible to install with pip ([described in the docs](https://github.com/olipo186/Git-Auto-Deploy/blob/development/docs/Install%20as%20a%20python%20module.md)) and even from a .deb package (which automatically installs init files, mostly created support for this since I was interested in trying out [stdeb](https://pypi.python.org/pypi/stdeb/0.8.5)).

I left the file GitAutoDeploy.py in the same location in the repo root for compatibility reasons, but will likely remove it further on, as GitAutoDeploy is now started using the python module ```gitautodeploy```.
