### ISSUE TITLE
Log feature

### ISSUE THREAD

**Issue by nomysz** [olipo186/Git-Auto-Deploy#99]
I suggest extending config with:

"log_file": "~/autodeploy.log"

Every line would contain date of triggered autodeploy and deploy details (like url, branch or key identyfing deploy config node).

Currently Im using global deploy command "echo Deploy triggered `date +'%d-%m-%Y %H:%M:%S'` >> /home/www/log/autodeploy.log", but it can be useful feature for debug.

**Comment by olipo186** [comment]
There is actually already an option for specifying a log file (https://github.com/olipo186/Git-Auto-Deploy/blob/master/docs/Configuration.md#configuration-file-options) that looks like this;

      "logfilepath": "~/gitautodeploy.log",

you can also specify the threshold to INFO to get less details;

    "log-level": "INFO",

This won't give the same result as your custom deploy command since it will generate ~5-10 lines per requests (with INFO), but is pretty close otherwise.

**Comment by olipo186** [comment]
@nomysz did it work out? :) Reopen otherwise.

**Comment by nomysz** [comment]
Sorry,
I didnt have a time for that, it was just a idea of feature :)When Ill have time ill try to solve it.

greetsSimon


    On Friday, May 13, 2016 6:39 PM, Oliver Poignant <notifications@github.com> wrote:
 

 @nomysz did it work out? :) Reopen otherwise.—
